spring.application.name=grampanchayat
# Server
#server.port=8087

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

spring.messages.basename=messages
spring.messages.encoding=UTF-8
spring.mvc.view.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.charset=UTF-8
spring.http.encoding.force=true
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
server.servlet.encoding.enabled=true
spring.servlet.multipart.max-file-size=1000MB
spring.servlet.multipart.max-request-size=1000MB
server.tomcat.max-swallow-size=-1
# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/grampanchayat
spring.datasource.username=root
spring.datasource.password=1998
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#logging.level.com.zaxxer.hikari=DEBUG
#logging.level.org.hibernate.SQL=DEBUG


# Security (for dev)
spring.security.user.name=admin
spring.security.user.password=admin123


complaint.image.upload.path=/opt/grampanchayat/complaintimages/
pdf.upload.path=/opt/grampanchayat/pdf/


#complaint.image.upload.path=C:/images/
#pdf.upload.path=C:/images/
sms.api.key=YOUR_FAST2SMS_API_KEY
mobile.country.code = 91
otp.whatsapp.api.url = https://backend.aisensy.com/campaign/t1/api/v2
otp.whatsapp.api.apiKey =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5YjgxYWZjNWE5Yzc3NDU4Y2ZhMjY3ZCIsIm5hbWUiOiJDb2RlT25lIFRlY2hub2xvZ3kgU29sdXRpb25zIDM4MjkiLCJhcHBOYW1lIjoiQWlTZW5zeSIsImNsaWVudElkIjoiNjliODFhZmM1YTljNzc0NThjZmEyNjc3IiwiYWN0aXZlUGxhbiI6IkJBU0lDX1lFQVJMWSIsImlhdCI6MTc3NjE4MTIyNH0.2bMPWeVYkcDz5hbK6tDzwSjlZKcUEaRCytCdrayoYJo
otp.whatsapp.api.campaignName =codeoneprimary

news.whatsapp.api.url =https://backend.aisensy.com/campaign/t1/api/v2
news.whatsapp.api.apiKey =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5YjgxYWZjNWE5Yzc3NDU4Y2ZhMjY3ZCIsIm5hbWUiOiJDb2RlT25lIFRlY2hub2xvZ3kgU29sdXRpb25zIDM4MjkiLCJhcHBOYW1lIjoiQWlTZW5zeSIsImNsaWVudElkIjoiNjliODFhZmM1YTljNzc0NThjZmEyNjc3IiwiYWN0aXZlUGxhbiI6IkJBU0lDX1lFQVJMWSIsImlhdCI6MTc3NjE4MTIyNH0.2bMPWeVYkcDz5hbK6tDzwSjlZKcUEaRCytCdrayoYJo
news.whatsapp.api.campaignName =codeoneprimaryutility

